# Generated by Django 3.2.5 on 2021-07-10 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventSpec', '0001_initial'),
        ('Users', '0002_auto_20210710_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertotalhour',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventSpec.event'),
        ),
        migrations.AlterField(
            model_name='usertotalhour',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
