# Generated by Django 3.2.5 on 2021-07-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='your_name',
        ),
    ]
