# Generated by Django 3.2.5 on 2021-07-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20210710_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsubmit',
            old_name='user',
            new_name='user_using',
        ),
    ]
