# Generated by Django 3.2.5 on 2021-07-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_rename_user_formsubmit_user_using'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='formsubmit',
            name='comment',
        ),
        migrations.AddField(
            model_name='formsubmit',
            name='others',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
