# Generated by Django 3.2.5 on 2021-07-10 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20210710_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmit',
            name='task_done',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Users.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
