# Generated by Django 3.2.5 on 2021-07-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_formsubmit_hours_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmit',
            name='others',
            field=models.CharField(blank=True, default='others', max_length=200),
        ),
    ]
