# Generated by Django 3.2.5 on 2021-07-10 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0011_alter_formsubmit_others'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckerAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_spent', models.IntegerField(default=0)),
                ('others', models.CharField(blank=True, default='  ', max_length=200)),
                ('upload', models.BooleanField(default='False')),
                ('task_done', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.task')),
                ('user_using', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
