# Generated by Django 3.2.5 on 2021-07-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_checkeradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkeradmin',
            name='total_hours_spent',
            field=models.IntegerField(default=0),
        ),
    ]
