# Generated by Django 3.2.5 on 2021-07-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_checkeradmin_total_hours_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmit',
            name='total_hours_spent',
            field=models.IntegerField(default=0),
        ),
    ]
