# Generated by Django 3.2.5 on 2021-07-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_usermetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmit',
            name='total_hours_spent',
        ),
    ]
