# Generated by Django 3.2.5 on 2021-07-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_remove_formsubmit_total_hours_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Total_hours_done',
            field=models.IntegerField(default=0),
        ),
    ]
