# Generated by Django 3.2.5 on 2021-07-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_task_total_hours_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='formsubmit',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics'),
        ),
    ]
