# Generated by Django 3.2.5 on 2021-07-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_blooddonor_brightsparkeducation_foodnutrition_genderprogram_transformers_youngistaananimalheroes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodDonor',
        ),
        migrations.DeleteModel(
            name='BrightSparkEducation',
        ),
        migrations.DeleteModel(
            name='FoodNutrition',
        ),
        migrations.DeleteModel(
            name='GenderProgram',
        ),
        migrations.DeleteModel(
            name='Transformers',
        ),
        migrations.DeleteModel(
            name='YoungistaanAnimalHeroes',
        ),
    ]
