# Generated by Django 3.2.5 on 2021-07-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventSpec', '0002_auto_20210710_1257'),
        ('Users', '0022_auto_20210710_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmit',
            name='task_done',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventSpec.brightsparkeducation'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
