# Generated by Django 3.2.5 on 2021-07-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0023_auto_20210710_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsubmit',
            old_name='task_done',
            new_name='task_choosen',
        ),
    ]
