# Generated by Django 3.2.5 on 2021-07-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventSpec', '0004_auto_20210710_1627'),
        ('Users', '0024_rename_task_done_formsubmit_task_choosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmit',
            name='task_choosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventSpec.task'),
        ),
    ]
