# Generated by Django 3.2.5 on 2021-07-10 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventSpec', '0005_auto_20210710_1627'),
        ('Users', '0026_profile_event_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='event_chosen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventSpec.event'),
        ),
    ]
