# Generated by Django 3.2.5 on 2021-07-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventSpec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blooddonor',
            old_name='Total_hours_done',
            new_name='Estimated_total_hours',
        ),
        migrations.RenameField(
            model_name='brightsparkeducation',
            old_name='Total_hours_done',
            new_name='Estimated_total_hours',
        ),
        migrations.RenameField(
            model_name='foodnutrition',
            old_name='Total_hours_done',
            new_name='Estimated_total_hours',
        ),
        migrations.RenameField(
            model_name='genderprogram',
            old_name='Total_hours_done',
            new_name='Estimated_total_hours',
        ),
        migrations.RenameField(
            model_name='transformers',
            old_name='Total_hours_done',
            new_name='Estimated_total_hours',
        ),
        migrations.RenameField(
            model_name='youngistaananimalheroes',
            old_name='Total_hours_done',
            new_name='Estimated_total_hours',
        ),
    ]
