# Generated by Django 3.2.5 on 2021-07-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventSpec', '0002_auto_20210710_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonor',
            name='locationOfOperation',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='brightsparkeducation',
            name='locationOfOperation',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='foodnutrition',
            name='locationOfOperation',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='genderprogram',
            name='locationOfOperation',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='transformers',
            name='locationOfOperation',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='youngistaananimalheroes',
            name='locationOfOperation',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
