# Generated by Django 3.2.5 on 2021-07-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0025_alter_formsubmit_task_choosen'),
        ('eventSpec', '0004_auto_20210710_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrightSparkEducation',
        ),
        migrations.DeleteModel(
            name='FoodNutrition',
        ),
        migrations.DeleteModel(
            name='GenderProgram',
        ),
        migrations.DeleteModel(
            name='Transformers',
        ),
        migrations.DeleteModel(
            name='YoungistaanAnimalHeroes',
        ),
        migrations.AddField(
            model_name='task',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventSpec.event'),
        ),
    ]
