# Generated by Django 3.2.5 on 2021-07-09 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_rename_comment_text_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='your_name',
            field=models.ForeignKey(default='q', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
