# Generated by Django 3.2.5 on 2021-07-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_your_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='your_name',
            field=models.CharField(max_length=20),
        ),
    ]
